test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.1e360398.name = "Upgrade from 4.12.0"

    test_upgrade_from.7a024ca1.name = "Upgrade from 5.3.0"
