test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    args.admin = "john"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4075742998b77f2b5d6251ee70b1e6336acb171e.name = "Upgrade from 5.3.0~ynh2"