test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    args.admin = "john"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2a54cd03.name = "Upgrade from 4.10.0"

    test_upgrade_from.1e360398.name = "Upgrade from 4.12.0"
