#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP APP MAIN DIR
#=================================================

CHECK_SIZE "$final_path"
ynh_backup "$final_path" "sources"

#=================================================
# BACKUP NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"

#=================================================
# BACKUP LOGROTATE CONFIGURATION
#=================================================
ynh_backup "/etc/logrotate.d/$app" "logrotate"

#=================================================
# BACKUP SYSTEMD CONFIGURATION
#=================================================

ynh_backup "/etc/systemd/system/$app.service" "systemd.service"
