#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE

#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

ynh_nodejs_remove

#=================================================
# REMOVE SANDBOX DOMAIN
#=================================================

# We don't test that in CI
if ! ynh_in_ci_tests; then

	# if the main domain for the app is a root domain, we create a correct sandbox subdomain
	if [[ $domain == *"."* ]]; then
		sandboxdomain=sandbox.$domain
	fi
	# if the main domain for the app is already a sub-domain, we create a correct sandbox domain
	if [[ $domain == *"."*"."* ]]; then
		sandboxdomain=sandbox-$domain
	fi
	# if the main domain for the app is a .local root domain, we create a correct sandbox subdomain
	if [[ $domain == *".local" ]]; then
		sandboxdomain=sandbox-$domain
	fi

	ynh_script_progression "Removing sandbox domain : $sandboxdomain"

	if yunohost domain list | grep -q $sandboxdomain
	then #if domain exist we remove it
		yunohost domain remove $sandboxdomain
		# we clean the nginx configuration we added
		ynh_safe_rm "/etc/nginx/conf.d/$sandboxdomain.d/"
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
