#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=3
	yunohost service remove $app
fi

ynh_remove_systemd_config

ynh_remove_nginx_config

ynh_remove_nodejs

#=================================================
# REMOVE SANDBOX DOMAIN
#=================================================

# We don't test that in CI
if ! [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
	
	# if the main domain for the app is a root domain, we create a correct sandbox subdomain
	if [[ $domain == *"."* ]]; then
		sandboxdomain=sandbox.$domain
	fi
	# if the main domain for the app is already a sub-domain, we create a correct sandbox domain
	if [[ $domain == *"."*"."* ]]; then
		sandboxdomain=sandbox-$domain
	fi
	# if the main domain for the app is a .local root domain, we create a correct sandbox subdomain
	if [[ $domain == *".local" ]]; then
		sandboxdomain=sandbox-$domain
	fi
	
	ynh_script_progression --message="Removing sandbox domain: $sandboxdomain" --weight=1
	
	if yunohost domain list | grep -q $sandboxdomain
	then # if domain exist we remove it
		yunohost domain remove $sandboxdomain
		# we clean the NGINX configuration we added
		ynh_secure_remove --file="/etc/nginx/conf.d/$sandboxdomain.d/"
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
