#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# MANAGING MIGRATIONS
#=================================================
ynh_script_progression "Managing migrations..."

# remove the legacy way to manage sandbox domain
if yunohost domain list --output-as plain | grep -q "sandbox\.${domain}"; then
	yunohost domain remove "sandbox.$domain"
	ynh_print_warn "Since some changes was done on the sandbox domain, you will need to regenerate the certificate for $domain and update your DNS config accordingly."
fi

if yunohost domain list --output-as plain | grep -q "sandbox-${domain}"; then
	yunohost domain remove "sandbox-$domain"
	ynh_print_warn "Since some changes was done on the sandbox domain, you will need to regenerate the certificate for $domain and update your DNS config accordingly."
fi

sandboxdomain=sandbox.$domain
ynh_app_setting_set --key=sandboxdomain --value="$sandboxdomain"

# Manage migration of data dir and logs
if [ ! -h "$install_dir/logs" ]; then
    ynh_script_progression "Moving logs..."
    if [ -e  "/var/log/$app" ]; then
        mv "/var/log/$app" "/var/log/${app}_$(date '+%Y%m%d.%H%M%S')"
    fi
    [ -e "$install_dir/data/logs" ] && mv "$install_dir/data/logs" "/var/log/$app"
    mkdir -p "/var/log/$app"
    chown -R "$app:$app" "/var/log/$app"
    chmod 750 "/var/log/$app"
fi
if [ ! -h "$install_dir/data" ]; then
    ynh_script_progression "Moving data into data dir..."

    if [ -n "$(ls -A "$data_dir")" ]; then
        old_data_dir_path="${data_dir}_$(date '+%Y%m%d.%H%M%S')"
        mkdir -p "$old_data_dir_path"
        mv -t "$old_data_dir_path" "$data_dir"/*
    fi

    mv -t "$data_dir" "$install_dir/data/"* || true
    ynh_safe_rm "$install_dir/data"

    test -e "$install_dir/datastore" && mv "$install_dir/datastore" "$data_dir/datastore"
    test -e "$install_dir/block"     && mv "$install_dir/block" "$data_dir/block"
    test -e "$install_dir/blob"      && mv "$install_dir/blob" "$data_dir/blob"
    chown -R "$app:$app" "$data_dir"
fi

ynh_app_setting_set_default --key=admin_keys --value=''

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --full_replace --dest_dir="$install_dir" --keep='customize onlyoffice-conf www/common/onlyoffice/dist'
ln -s "/var/log/$app" "$install_dir/logs"
ln -s "$data_dir" "$install_dir/data"

#=================================================
# APPLY FOLDER GROUP RIGHTS FOR WWW-DATA
#=================================================

chgrp -R www-data $install_dir

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add --template=nginx-sandbox.conf --destination=/etc/nginx/conf.d/sandbox."$domain".conf
ynh_config_add --template=nginx-shared.conf --destination=/etc/nginx/conf.d/"$app"-shared.conf.inc

chown www-data:www-data /etc/nginx/conf.d/sandbox."$domain".conf
chown www-data:www-data /etc/nginx/conf.d/"$app"-shared.conf.inc

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Zero Knowledge realtime collaborative editor" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL CRYPTPAD
#=================================================
ynh_script_progression "Building $app... (this will take some time and resources!)"

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm ci
	ynh_hide_warnings ynh_exec_as_app npm run install:components
	ynh_hide_warnings ynh_exec_as_app npm run build
	ynh_hide_warnings bash install-onlyoffice.sh --accept-license
popd

#=================================================
# ADD UPGRADED CONFIG WITH SANDBOX
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --jinja --template="config.js" --destination="$install_dir/config/config.js"

chmod 600 "$install_dir/config/config.js"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
